//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sınıflarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalDetails
    {
        public int Id { get; set; }
        public int AnimalId { get; set; }
        public string Breed { get; set; }
        public Nullable<bool> IsVaccinated { get; set; }
        public Nullable<bool> IsAnimalHomeless { get; set; }
        public string Details { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
