//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siniflarim
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalInfo
    {
        public int Id { get; set; }
        public Nullable<bool> vaccination { get; set; }
        public Nullable<System.DateTime> vaccineDate { get; set; }
        public string disease { get; set; }
    }
}
